def get_selectors():
    return {
        'username': 'username',
        'password': 'password',
        'button_login': '#react-root > section > main > div > article > div > div:nth-child(1) > div > form > div:nth-child(4) > button',
        'login_error': 'slfErrorAlert',
        'search_user': 'queryBox',
        'send': 'button',
        'select_user': '.-qQT3-',
        'notification_btn': 'body > div.RnEpo.Yx5HN > div > div > div.mt3GC > button.aOOlW.HoLwm',
        'page_exists_err': 'div > h2',
        'private_account_err': 'div#react-root div._4Kbb_ > div > h2',
        'comment_textarea': 'textarea.Ypffh',
        'like_btn': 'span.fr66n > button[type="button"] > svg',
        'follow_btn': "//*[text()='Follow']",
        'follow_btn_b': "//*[text()='Follow Back']",
        'get_suggested_url': 'https://www.instagram.com/explore/people/suggested/',
        'scroll_to_btm': 'window.scrollTo(0, document.body.scrollHeight);',
        'hashtag_link': 'div#react-root div:nth-child(replacethisfirstnum) > div > div:nth-child(replacethisecondnum) > div:nth-child(replacethisthirdnum) > a',
        'suggestion_selector': 'div#react-root div:nth-child(replacethisStringse) > div.Igw0E.IwRSH.YBx95.vwCYk > div:nth-child(1) > div > a > div > div > div',
        'self_profile': 'https://www.instagram.com/replacethistring/',
        'tag_url': 'https://www.instagram.com/explore/tags/replacethistring/',
        'feed_posts': '#react-root > section > main > section > div > div:nth-child(3) > div > article',
        'insta': 'https://www.instagram.com/',
        'liked_color': '#ed4956',
        'feed_post': 'div.eo2As > section:nth-child(1) > span:nth-child(1) > button',
        'followers_count': '//*[@id="react-root"]/section/main/div/header/section/ul/li[2]/a/span',
        'following_count': '//*[@id="react-root"]/section/main/div/header/section/ul/li[3]/a/span',
        'hashtag_follow': '//*[@id="react-root"]/section/main/div/div/article/header/div[2]/div[1]/div[1]/a',
        'hashtag_string': '//*[@id="react-root"]/section/main/header/div[2]/div[2]/span/span[2]'
    }
